routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DeleteUser;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\personTaskController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\WorkspaceController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('features', function () {
    return view('features');
})->name('features');

Route::get('help', function () {
    return view('sendMail.help');
})->name('help');



// Mail Send
Route::post('sendHelp', [MailController::class, 'index']);


Auth::routes();

// Profile
Route::middleware(['auth'])->group(function () {
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::resource('profile',ProfileController::class);
});

// Dashboard
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
});

// Workspaces
Route::middleware(['auth'])->group(function () {
    Route::get('/workspace', [WorkspaceController::class, 'index'])->name('workspace');
    Route::get('getWorkspaces', [WorkspaceController::class, 'getData'])->name('workspaces.getData');
    Route::resource('workspaces',WorkspaceController::class);
    // Route::get('/search-users', [WorkspaceController::class, 'searchUser'])->name('search.users');
});

Route::post('deleteUser', DeleteUser::class)->name('deleteUser');

// Tasks
Route::middleware(['auth'])->group(function () {
    Route::get('/task', [TaskController::class, 'index'])->name('task');
    Route::resource('tasks',TaskController::class);
});

//Category
Route::middleware(['auth'])->group(function () {
    Route::get('/category', [CategoryController::class, 'index'])->name('category');
    Route::resource('categories',CategoryController::class);
});

//Personal Task
Route::middleware(['auth'])->group(function () {
    Route::get('/persontask', [personTaskController::class, 'index'])->name('persontask');
    Route::resource('persontasks',personTaskController::class);
});

app/Models/Workspace.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Workspace extends Model
{
    use HasFactory;

    // public function users(){
    //     return $this->belongsTo(User::class)->hasMany(Members::class)->hasMany(Tasks::class);
    // }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function member(){
        return $this->hasMany(Member::class);
    }

    public function task(){
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/WorkspaceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Member;
use App\Models\Task;
use App\Models\User;
use App\Models\Workspace;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use RealRashid\SweetAlert\Facades\Alert;

class WorkspaceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $sessionId = auth()->user()->id;

        $availabe = DB::table('members')->select('members.*')->where('members.user_id','=', $sessionId)->get();


        // $workspace = Member::all();
        // $workspace = Member::find($sessionId);

        // $detail = Workspace::find($workspace);

        confirmDelete();

        return view('workspaces.index',[
            'available' => $availabe,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $sessionId = auth()->user()->id;


        return view('workspaces.createWorkspace',['user_id' => $sessionId]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $messages = [
            'required' => 'Please input Workspace Name',
        ];

        $validator = Validator::make($request->all(), [
            'workspaceName' => 'required',
        ], $messages);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }


        $sessionId = auth()->user()->id;

        $workspace = New Workspace;
        $workspace->user_id = $request->user_id;
        $workspace->namaWorkspace = $request->workspaceName;
        $workspace->deskWorkspace = $request->workspaceDesc;
        $workspace->save();


        $member = New Member;
        $member->workspace_id = $workspace->id;
        $member->user_id = $sessionId;
        $member->level = '1';
        $member->save();

        Alert::toast('Workspace Created', 'success');

        return redirect()->route('workspaces.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $sessionId = auth()->user()->id;
        $workspace = Workspace::find($id);

        $member = Member::all()->where('workspace_id','=',$workspace->id)->pluck('user_id');

        $usersName = User::all()->whereIn('id',$member);

        $task = Task::all()->whereIn('workspace_id',$workspace->id);

        return view('workspaces.detail', compact('workspace','sessionId','member','usersName','task'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $sessionId = auth()->user()->id;
        $workspace = Workspace::find($id);

        $member = Member::all()->where('workspace_id','=',$workspace->id)->pluck('user_id');

        $usersName = User::all()->whereIn('id',$member);

        if ($workspace->user_id == $sessionId){
            $user = User::all();
            return view('workspaces.edit', compact('workspace','sessionId','user','usersName'));

        }else{
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $messages = [
            'required' => 'Please input Workspace Name',
        ];

        $validator = Validator::make($request->all(), [
            'workspaceName' => 'required',
        ], $messages);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }

        $workspace = Workspace::find($id);
        $workspace->user_id = $request->user_id;
        $workspace->namaWorkspace = $request->workspaceName;
        $workspace->deskWorkspace = $request->workspaceDesc;
        $workspace->save();

        $new = $request->newName;

        if (!empty($new)) {
            $member = New Member;
            $member->workspace_id = $workspace->id;
            $member->user_id = $new;
            $member->level = '0';
            $member->save();
        }

        Alert::toast('Workspace Updated','success');

        return redirect()->route('workspaces.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $sessionId = auth()->user()->id;

        $work = Workspace::find($id);

        if ($work->user_id == $sessionId){
            $work->delete();
        }
        else{
            return redirect()->route('workspaces.index');
        }

        Alert::toast('Workspace Deleted', 'success');

        return redirect()->route('workspaces.index');
    }

    public function getData(Request $request)
    {
        $sessionId = auth()->user()->id;

        // ELOQUENT
        $detail = Member::where('user_id','=',$sessionId)
        ->pluck('workspace_id');

        // ELOQUENT
        $workspace = Workspace::whereIn('id', $detail);

        if ($request->ajax()) {
            return datatables()->of($workspace)
                ->addIndexColumn()
                ->addColumn('actions', function ($workspace) {
                    // Query to get the level for the current workspace and user
                    $sessionId = auth()->user()->id;
                    $level = Member::where('workspace_id', '=', $workspace->id)->where('user_id','=',$sessionId);
                    return view('workspaces.actions', compact('workspace','level'));
                })
                ->toJson();
        }
    }

    // public function searchUser(Request $request){

    //     $q = $request->input('q');

    //     $users = User::where('email', 'like', '%'.$q.'%')->select('id', 'email')->get();

    //     return response()->json($users);
    // }
}

resources/views/workspaces/workTasks/taskEdit.blade.php
    @extends('layouts.sidebar')
    @section('content')
    <div class="container-sm">
        <h3 class="mt-3">Update Task</h3>
        {{-- <h3 class="mt-3">{{ $task }}</h3> --}}
        <form action="{{ route('tasks.update', ['task' => $task->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input type="" class="form-control" id="workId" name="workId" value="{{ $task->workspace_id }}" hidden>
            <div class="mb-3">
              <label for="taskName" class="form-label">Task Name</label>
              <input type="" class="form-control @error('taskName') is-invalid @enderror" id="taskName" name="taskName" value="{{ $task->namaTask }}">
              @error ('taskName') <div class="fs-3 text-danger">{{ $message }}</div> @enderror
            </div>
            <div class="mb-3">
              <label for="startDate" class="form-label">Start Date</label>
              <input type="date" class="form-control" id="startDate" name="startDate" value="{{ $task->startDate }}">
            </div>
            <div class="mb-3">
              <label for="dueDate" class="form-label">Due Date</label>
              <input type="date" class="form-control" id="dueDate" name="dueDate" value="{{ $task->dueDate }}">
            </div>
            <div class="mb-3">
                <label for="status" class="form-label">Status</label>
                <select id="status" name="status" class="form-select">
                  <option value="pending">Pending</option>
                  <option value="onprogress">On-Progress</option>
                  <option value="done">Done</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
    @endsection

resources/views/workspaces/workTasks/taskIndex.blade.php
    @extends('layouts.sidebar')
    @section('content')
    <div class="container-sm">
        <h3 class="mt-3">Create Task</h3>
        {{-- <h3 class="mt-3">{{ $workId }}</h3> --}}
        <form action="{{ route('tasks.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="" class="form-control" id="workId" name="workId" value="{{ $workId }}" hidden>
            <div class="mb-3">
              <label for="taskName" class="form-label">Task Name</label>
              <input type="" class="form-control @error('taskName') is-invalid @enderror" id="taskName" name="taskName" placeholder="New Task name">
              @error ('taskName') <div class="fs-3 text-danger">{{ $message }}</div> @enderror
            </div>
            <div class="mb-3">
              <label for="startDate" class="form-label">Start Date</label>
              <input type="date" class="form-control" id="startDate" name="startDate">
            </div>
            <div class="mb-3">
              <label for="dueDate" class="form-label">Due Date</label>
              <input type="date" class="form-control" id="dueDate" name="dueDate">
            </div>
            <div class="mb-3">
                <label for="status" class="form-label">Status</label>
                <select id="status" name="status" class="form-select">
                  <option value="pending">Pending</option>
                  <option value="onprogress">On-Progress</option>
                  <option value="done">Done</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
    @endsection