routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DeleteUser;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\personTaskController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\WorkspaceController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('features', function () {
    return view('features');
})->name('features');

Route::get('help', function () {
    return view('sendMail.help');
})->name('help');



// Mail Send
Route::post('sendHelp', [MailController::class, 'index']);


Auth::routes();

// Profile
Route::middleware(['auth'])->group(function () {
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::resource('profile',ProfileController::class);
});

// Dashboard
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
});

// Workspaces
Route::middleware(['auth'])->group(function () {
    Route::get('/workspace', [WorkspaceController::class, 'index'])->name('workspace');
    Route::get('getWorkspaces', [WorkspaceController::class, 'getData'])->name('workspaces.getData');
    Route::resource('workspaces',WorkspaceController::class);
    // Route::get('/search-users', [WorkspaceController::class, 'searchUser'])->name('search.users');
});

Route::post('deleteUser', DeleteUser::class)->name('deleteUser');

// Tasks
Route::middleware(['auth'])->group(function () {
    Route::get('/task', [TaskController::class, 'index'])->name('task');
    Route::resource('tasks',TaskController::class);
});

//Category
Route::middleware(['auth'])->group(function () {
    Route::get('/category', [CategoryController::class, 'index'])->name('category');
    Route::resource('categories',CategoryController::class);
});

//Personal Task
Route::middleware(['auth'])->group(function () {
    Route::get('/persontask', [personTaskController::class, 'index'])->name('persontask');
    Route::resource('persontasks',personTaskController::class);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public function persontask(){
        return $this->hasMany(personTask ::class);
    }
    public function user(){
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use RealRashid\SweetAlert\Facades\Alert;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $sessionId = auth()->user()->id;

        $category = Category::all()->whereIn('user_id', $sessionId);

        confirmDelete();

        return view('categories.index',['category'=>$category]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('categories.createCategory');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $sessionId = auth()->user()->id;

        $messages = [
            'required' => 'Category name cannot be empty',
        ];

        $validator = Validator::make($request->all(), [
            'category' => 'required',
        ], $messages);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }


        $category = New Category;
        $category->user_id = $sessionId;
        $category->categoryName = $request->category;
        $category->save();

        Alert::toast('Category Added', 'success');

        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        // $sessionId = auth()->user()->id;

        Category::find($id)->delete();

        Alert::toast('Category Deleted', 'success');

        return redirect()->route('categories.index');
    }
}

resources/views/categories/index.blade.php
@extends('layouts.sidebar')

@section('content')
<div class="container-sm">
    <h3 class="mt-3">Category</h3>

    <div class="table-responsive border p-3 rounded-3 mb-3 mt-3">
        <div class="text-end">
            {{-- {{ $category }} --}}
            <form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <input type="text" class="form-control @error('category') is-invalid @enderror" id="category" name="category" value="" placeholder="Add new Category">
                @error ('category') <div class="fs-3 text-danger">{{ $message }}</div> @enderror
                <button type="submit" class="btn btn-primary my-2">Add New Category</button>
            </form>
        </div>
        <table class="table table-hover table-striped bg-white categtable" id="categtable">
            <thead class="text-center">
                <tr>
                    <th>Category</th>
                    <th>#</th>
                </tr>
            </thead>
            @foreach ( $category as $categories)
            <tbody class="text-center">
                <tr>
                    <td>{{ $categories->categoryName }}</td>
                    <td>
                        <form action="{{ route('categories.destroy', ['category' => $categories->id]) }}" method="POST">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-outline-dark btn-sm me-2 btn-delete">
                                <i class="bi-trash"></i>
                            </button>
                        </form>
                    </td>
                </tr>
            </tbody>
            @endforeach
        </table>
    </div>
</div>
@endsection

@push('scripts')
    <script type="module">
        $(document).ready(function() {
            $(".categtable").on("click", ".btn-delete", function (e) {
                e.preventDefault();

                var form = $(this).closest("form");

                Swal.fire({
                    title: "Are you sure want to delete ?",
                    text: "You won't be able to revert this!",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "bg-primary",
                    confirmButtonText: "Yes, delete it!",
                }).then((result) => {
                    if (result.isConfirmed) {
                        form.submit();
                    }
                });
            });
        });
    </script>
@endpush