routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DeleteUser;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\personTaskController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\WorkspaceController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('features', function () {
    return view('features');
})->name('features');

Route::get('help', function () {
    return view('sendMail.help');
})->name('help');



// Mail Send
Route::post('sendHelp', [MailController::class, 'index']);


Auth::routes();

// Profile
Route::middleware(['auth'])->group(function () {
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::resource('profile',ProfileController::class);
});

// Dashboard
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
});

// Workspaces
Route::middleware(['auth'])->group(function () {
    Route::get('/workspace', [WorkspaceController::class, 'index'])->name('workspace');
    Route::get('getWorkspaces', [WorkspaceController::class, 'getData'])->name('workspaces.getData');
    Route::resource('workspaces',WorkspaceController::class);
    // Route::get('/search-users', [WorkspaceController::class, 'searchUser'])->name('search.users');
});

Route::post('deleteUser', DeleteUser::class)->name('deleteUser');

// Tasks
Route::middleware(['auth'])->group(function () {
    Route::get('/task', [TaskController::class, 'index'])->name('task');
    Route::resource('tasks',TaskController::class);
});

//Category
Route::middleware(['auth'])->group(function () {
    Route::get('/category', [CategoryController::class, 'index'])->name('category');
    Route::resource('categories',CategoryController::class);
});

//Personal Task
Route::middleware(['auth'])->group(function () {
    Route::get('/persontask', [personTaskController::class, 'index'])->name('persontask');
    Route::resource('persontasks',personTaskController::class);
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    public function workspace(){
        return $this->belongsTo(Workspace::class);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Member;
use App\Models\Task;
use App\Models\Workspace;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Ramsey\Uuid\Type\Integer;
use RealRashid\SweetAlert\Facades\Alert;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {

        confirmDelete();

        return view('workspaces.detail');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // $sessionId = auth()->user()->id;

        $messages = [
            'required' => 'Please input Task Name',
        ];

        $validator = Validator::make($request->all(), [
            'taskName' => 'required',
        ], $messages);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }

        $task = New Task;
        $task->workspace_id = $request->workId;
        $task->namaTask = $request->taskName;
        $task->startDate = $request->startDate;
        $task->dueDate = $request->dueDate;
        $task->status = $request->status;
        $task->save();

        Alert::toast('Task Created', 'success');

        return redirect()->route('workspaces.show',['workspace' => $task->workspace_id]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        // $sessionId = auth()->user()->id;

        $workspace = Workspace::find($id);

        return view('workspaces.workTasks.taskIndex', ['workId' => $workspace->id]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $task = Task::find($id);

        return view('workspaces.workTasks.taskEdit', [
            'task' => $task,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $messages = [
            'required' => 'Task name cannot be empty',
        ];

        $validator = Validator::make($request->all(), [
            'taskName' => 'required',
        ], $messages);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }

        $task = Task::find($id);
        $task->workspace_id = $request->workId;
        $task->namaTask = $request->taskName;
        $task->startDate = $request->startDate;
        $task->dueDate = $request->dueDate;
        $task->status = $request->status;
        $task->save();

        Alert::toast('Task Updated', 'success');

        return redirect()->route('workspaces.show',['workspace' => $task->workspace_id]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Task::find($id)->delete();
        // $workspace = Workspace::find($id);

        Alert::toast('Task Deleted', 'success');

        return back();
    }
}

resources/views/tasks/createTask.blade.php
    @extends('layouts.sidebar')

    @section('content')
    <div class="container-sm">
        <h3 class="mt-3">Create Personal Task</h3>
        {{-- <h3 class="mt-3">{{ $category }}</h3> --}}
        <form action="{{ route('persontasks.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="mb-3">
              <label for="namaTask" class="form-label">Task Name</label>
              <input type="" class="form-control @error('taskName') is-invalid @enderror" id="taskName" name="taskName" placeholder="New Task name">
              @error ('taskName') <div class="fs-3 text-danger">{{ $message }}</div> @enderror
            </div>
            <div class="mb-3">
              <label for="startDate" class="form-label">Start Date</label>
              <input type="date" class="form-control" id="startDate" name="startDate">
            </div>
            <div class="mb-3">
              <label for="dueDate" class="form-label">Due Date</label>
              <input type="date" class="form-control" id="dueDate" name="dueDate">
            </div>
            <div class="mb-3">
                <label for="status" class="form-label">Status</label>
                <select id="status" name="status" class="form-select">
                  <option value="pending">Pending</option>
                  <option value="onprogress">On-Progress</option>
                  <option value="done">Done</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="category" class="form-label">Category</label>
                <select id="category" name="category" class="form-select">
                    <option value="" selected>Add category</option>
                    @foreach ($category as $categories )
                    <option value="{{ $categories->id }}">{{ $categories->categoryName }}</option>
                    @endforeach
                </select>
                @if (count($category) == 0)
                    <p class="text-danger">You haven't added any <a href="{{ route ('category') }}" class="text-info">category</a></p>
                @endif
            </div>
            <button type="submit" class="btn btn-primary">Create new Task</button>
            <a href="{{ route ('persontask') }}" type="button" id="submit" name="submit" class="btn btn-secondary">Cancel</a>
          </form>
    </div>
    @endsection

resources/views/tasks/editTask.blade.php
    @extends('layouts.sidebar')

    @section('content')
    <div class="container-sm">
        <h3 class="mt-3">Create Task</h3>
        {{-- <h3 class="mt-3">{{ $task }}</h3> --}}
        <form action="{{ route('persontasks.update', ['persontask' => $task->id]) }}" method="POST" enctype="multipart/form-data" id="updateForm{{$task->id}}">
            @csrf
            @method('PUT')
            <div class="mb-3">
              <label for="taskName" class="form-label">Task Name</label>
              <input type="text" class="form-control @error('taskName') is-invalid @enderror" id="taskName" name="taskName" value="{{ $task->namaTask }}">
              @error ('taskName') <div class="fs-3 text-danger">{{ $message }}</div> @enderror
            </div>
            <div class="mb-3">
              <label for="startDate" class="form-label">Start Date</label>
              <input type="date" class="form-control" id="startDate" name="startDate" value="{{ $task->startDate }}">
            </div>
            <div class="mb-3">
              <label for="dueDate" class="form-label">Due Date</label>
              <input type="date" class="form-control" id="dueDate" name="dueDate" value="{{ $task->dueDate }}">
            </div>
            <div class="mb-3">
                <label for="status" class="form-label">Status</label>
                <select id="status" name="status" class="form-select">
                  <option value="pending">Pending</option>
                  <option value="onprogress">On-Progress</option>
                  <option value="done">Done</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="category" class="form-label">Category</label>
                <select id="category" name="category" class="form-select">
                    @foreach ($category as $categories )
                     <option value="{{ $categories->id }}">{{ $categories->categoryName }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
          </form>
    </div>
    @endsection

resources/views/tasks/index.blade.php
    @extends('layouts.sidebar')

    @section('content')

        @if(session()->has('deleteSuccess'))
        <script>
            Swal.fire(
            'Succes deleted',
            'Your file has been deleted.',
            'success')
        </script>
        @endif

        @if(session()->has('updateSuccess'))
        <script>
            Swal.fire(
            'updated',
            'Your file has been updated.',
            'success')
        </script>
        @endif

        @vite('resources/js/datatable.js')
    <div class="container-sm">
        <div class="d-flex justify-content-between align-items-center">
            <h3 class="mt-3">Personal Task</h3>
        </div>
        <div class="table-responsive border p-3 rounded-3 mb-3">
            {{-- {{ $persontask }} --}}
            <a href="{{ route('persontasks.create') }}" class="btn btn-outline-primary mb-3">Create new Task</a>
            <table class="table table-hover table-striped bg-white personTable" id="personTable">
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Start Date</th>
                        <th>Due Date</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                @foreach ( $persontask as $tasks )
                    <tr>
                        <td>{{ $tasks->namaTask }}</td>
                        <td>{{ $tasks->startDate }}</td>
                        <td>{{ $tasks->dueDate }}</td>
                        @if ($tasks->category_id == null)
                            <td></td>
                        @else
                            <td>{{ $tasks->category->categoryName }}</td>
                        @endif
                        <td>{{ $tasks->status }}</td>
                        <td>
                            <div class="d-flex">
                                <a href="{{ route('persontasks.edit',['persontask' => $tasks->id]) }}" class="btn btn-outline-dark btn-sm me-2"><i class="bi-pencil-square"></i></a>
                                <form action="{{ route('persontasks.destroy',['persontask' => $tasks->id]) }}" method="POST">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-outline-dark btn-sm me-2 btn-delete">
                                    <i class="bi-trash"></i>
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @endsection
    @push('scripts')
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.3.2/js/dataTables.fixedHeader.min.js"></script>
        <script type="module">
            $(document).ready(function() {
                $("#personTable").DataTable({
                    responsive: true,
                    searching: true,
                    paging: false,
                    info: false
                });

                $(".personTable").on("click", ".btn-delete", function (e) {
                    e.preventDefault();

                    var form = $(this).closest("form");

                    Swal.fire({
                        title: "Are you sure want to delete ?",
                        text: "You won't be able to revert this!",
                        icon: "warning",
                        showCancelButton: true,
                        confirmButtonClass: "bg-primary",
                        confirmButtonText: "Yes, delete it!",
                    }).then((result) => {
                        if (result.isConfirmed) {
                            form.submit();
                        }
                    });
                });
            });
        </script>
    @endpush