routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DeleteUser;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\personTaskController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\WorkspaceController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('features', function () {
    return view('features');
})->name('features');

Route::get('help', function () {
    return view('sendMail.help');
})->name('help');



// Mail Send
Route::post('sendHelp', [MailController::class, 'index']);


Auth::routes();

// Profile
Route::middleware(['auth'])->group(function () {
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::resource('profile',ProfileController::class);
});

// Dashboard
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
});

// Workspaces
Route::middleware(['auth'])->group(function () {
    Route::get('/workspace', [WorkspaceController::class, 'index'])->name('workspace');
    Route::get('getWorkspaces', [WorkspaceController::class, 'getData'])->name('workspaces.getData');
    Route::resource('workspaces',WorkspaceController::class);
    // Route::get('/search-users', [WorkspaceController::class, 'searchUser'])->name('search.users');
});

Route::post('deleteUser', DeleteUser::class)->name('deleteUser');

// Tasks
Route::middleware(['auth'])->group(function () {
    Route::get('/task', [TaskController::class, 'index'])->name('task');
    Route::resource('tasks',TaskController::class);
});

//Category
Route::middleware(['auth'])->group(function () {
    Route::get('/category', [CategoryController::class, 'index'])->name('category');
    Route::resource('categories',CategoryController::class);
});

//Personal Task
Route::middleware(['auth'])->group(function () {
    Route::get('/persontask', [personTaskController::class, 'index'])->name('persontask');
    Route::resource('persontasks',personTaskController::class);
});

app/Models/Workspace.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Workspace extends Model
{
    use HasFactory;

    // public function users(){
    //     return $this->belongsTo(User::class)->hasMany(Members::class)->hasMany(Tasks::class);
    // }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function member(){
        return $this->hasMany(Member::class);
    }

    public function task(){
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/WorkspaceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Member;
use App\Models\Task;
use App\Models\User;
use App\Models\Workspace;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use RealRashid\SweetAlert\Facades\Alert;

class WorkspaceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $sessionId = auth()->user()->id;

        $availabe = DB::table('members')->select('members.*')->where('members.user_id','=', $sessionId)->get();


        // $workspace = Member::all();
        // $workspace = Member::find($sessionId);

        // $detail = Workspace::find($workspace);

        confirmDelete();

        return view('workspaces.index',[
            'available' => $availabe,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $sessionId = auth()->user()->id;


        return view('workspaces.createWorkspace',['user_id' => $sessionId]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $messages = [
            'required' => 'Please input Workspace Name',
        ];

        $validator = Validator::make($request->all(), [
            'workspaceName' => 'required',
        ], $messages);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }


        $sessionId = auth()->user()->id;

        $workspace = New Workspace;
        $workspace->user_id = $request->user_id;
        $workspace->namaWorkspace = $request->workspaceName;
        $workspace->deskWorkspace = $request->workspaceDesc;
        $workspace->save();


        $member = New Member;
        $member->workspace_id = $workspace->id;
        $member->user_id = $sessionId;
        $member->level = '1';
        $member->save();

        Alert::toast('Workspace Created', 'success');

        return redirect()->route('workspaces.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $sessionId = auth()->user()->id;
        $workspace = Workspace::find($id);

        $member = Member::all()->where('workspace_id','=',$workspace->id)->pluck('user_id');

        $usersName = User::all()->whereIn('id',$member);

        $task = Task::all()->whereIn('workspace_id',$workspace->id);

        return view('workspaces.detail', compact('workspace','sessionId','member','usersName','task'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $sessionId = auth()->user()->id;
        $workspace = Workspace::find($id);

        $member = Member::all()->where('workspace_id','=',$workspace->id)->pluck('user_id');

        $usersName = User::all()->whereIn('id',$member);

        if ($workspace->user_id == $sessionId){
            $user = User::all();
            return view('workspaces.edit', compact('workspace','sessionId','user','usersName'));

        }else{
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $messages = [
            'required' => 'Please input Workspace Name',
        ];

        $validator = Validator::make($request->all(), [
            'workspaceName' => 'required',
        ], $messages);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }

        $workspace = Workspace::find($id);
        $workspace->user_id = $request->user_id;
        $workspace->namaWorkspace = $request->workspaceName;
        $workspace->deskWorkspace = $request->workspaceDesc;
        $workspace->save();

        $new = $request->newName;

        if (!empty($new)) {
            $member = New Member;
            $member->workspace_id = $workspace->id;
            $member->user_id = $new;
            $member->level = '0';
            $member->save();
        }

        Alert::toast('Workspace Updated','success');

        return redirect()->route('workspaces.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $sessionId = auth()->user()->id;

        $work = Workspace::find($id);

        if ($work->user_id == $sessionId){
            $work->delete();
        }
        else{
            return redirect()->route('workspaces.index');
        }

        Alert::toast('Workspace Deleted', 'success');

        return redirect()->route('workspaces.index');
    }

    public function getData(Request $request)
    {
        $sessionId = auth()->user()->id;

        // ELOQUENT
        $detail = Member::where('user_id','=',$sessionId)
        ->pluck('workspace_id');

        // ELOQUENT
        $workspace = Workspace::whereIn('id', $detail);

        if ($request->ajax()) {
            return datatables()->of($workspace)
                ->addIndexColumn()
                ->addColumn('actions', function ($workspace) {
                    // Query to get the level for the current workspace and user
                    $sessionId = auth()->user()->id;
                    $level = Member::where('workspace_id', '=', $workspace->id)->where('user_id','=',$sessionId);
                    return view('workspaces.actions', compact('workspace','level'));
                })
                ->toJson();
        }
    }

    // public function searchUser(Request $request){

    //     $q = $request->input('q');

    //     $users = User::where('email', 'like', '%'.$q.'%')->select('id', 'email')->get();

    //     return response()->json($users);
    // }
}

resources/views/workspaces/actions.blade.php
@php
    $currentRouteName = Route::currentRouteName();
@endphp

    @if ($level->pluck('level')->first() == '1')
        <div class="d-flex">
            <a href="{{ route('workspaces.show', ['workspace' => $workspace->id]) }}" class="btn btn-outline-dark btn-sm me-2">
                <i class="bi bi-folder2-open"></i>
            </a>
            <a href="{{ route('workspaces.edit', ['workspace' => $workspace->id]) }}" class="btn btn-outline-dark btn-sm me-2">
                <i class="bi-pencil-square"></i>
            </a>
            <div>
                <form action="{{ route('workspaces.destroy', ['workspace' => $workspace->id]) }}" method="POST">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-outline-dark btn-sm me-2 btn-delete">
                        <i class="bi-trash"></i>
                    </button>
                </form>
            </div>
        </div>
    @else
        <a href="{{ route('workspaces.show', ['workspace' => $workspace->id]) }}" class="btn btn-outline-dark btn-sm me-2">
            <i class="bi bi-folder2-open"></i>
        </a>
    @endif

resources/views/workspaces/createWorkspace.blade.php
    @extends('layouts.sidebar')
    @section('content')
    <div class="container-sm">
        <h3 class="mt-3">Create Workspace</h3>
        <form action="{{ route('workspaces.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="" class="form-control" id="user_id" name="user_id" value="{{ $user_id }}" hidden>
            <div class="mb-3">
              <label for="workspaceName" class="form-label">Workspace's Name</label>
              <input type="text" class="form-control @error('workspaceName') is-invalid @enderror" id="workspaceName" name="workspaceName" placeholder="New Workspace name">
              @error ('workspaceName') <div class="fs-3 text-danger">{{ $message }}</div> @enderror
            </div>
            <div class="mb-3">
              <label for="workspaceDesc" class="form-label">Description</label>
              <textarea class="form-control" id="workspaceDesc" style="height: 100px" name="workspaceDesc" placeholder="Input Description here"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{{ route ('workspace') }}" type="button" id="submit" name="submit" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
    @endsection

resources/views/workspaces/detail.blade.php
    @extends('layouts.sidebar')
    @section('content')
    <style>
        #scroll {
            -ms-overflow-style: none;
            scrollbar-width: none;
        }

        #scroll::-webkit-scrollbar {
            display: none !important;
        }
    </style>
    <div class="container-sm">
        @vite('resources/js/datatable.js')
        <h3 class="mt-3">Detail Workspace</h3>
        <div class="border p-3 rounded-2 mb-2">
            <p class="fw-bolder">Workspace: <br>
                <span>{{ $workspace->namaWorkspace }}</span>
            </p>
            <p class="fw-bolder">Description: <br>
                <span>{{ $workspace->deskWorkspace }}</span>
            </p>
            <div class="card-footer">
                <p>Member Lists</p>
                {{-- {{ $usersName }} --}}
                <div style="height: 100px" class="card-footer overflow-y-scroll" id="scroll">
                    <table class="table table-striped table-hover">
                        @foreach ( $usersName as $name )
                        <tr>
                            <td>{{ $name->name }}</td>
                            <td>{{ $name->email }}</td>
                            @if ($name->member->where('workspace_id','=',$workspace->id)->pluck('level')->first() == '1')
                            <td>Owner</td>
                            @else
                            <td>Member</td>
                            @endif
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>

        <div class="border p-3 rounded-2 mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <h6 class="mt-3">Tasks</h6>
            </div>
            <div class="table-responsive border p-3 rounded-3 mb-3">
                <a href="{{ route ('tasks.show',['task' => $workspace->id])}}" class="btn btn-outline-primary">Create new Task</a>
                {{-- {{ $member }} --}}
                <div style="max-height: 40vh;" class="table-responsive mb-3 overflow-y-scroll" id="scroll">
                    <table class="table table-hover table-striped bg-white tasktable" id="taskTable">
                        <thead>
                            <tr>
                                <th>Task</th>
                                <th>Start-Date</th>
                                <th>Due-Date</th>
                                <th>Status</th>
                                <th>#</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($task as $tasks )
                            <tr>
                                <td>{{ $tasks->namaTask }}</td>
                                <td>{{ $tasks->startDate }}</td>
                                <td>{{ $tasks->dueDate }}</td>
                                <td>{{ $tasks->status }}</td>
                                <td>
                                    <div class="d-flex">
                                        <a href="{{ route('tasks.edit', [$tasks->id]) }}" class="btn btn-outline-dark btn-sm me-2"><i class="bi-pencil-square"></i></a>
                                        <div>
                                            <form action="{{ route('tasks.destroy', [$tasks->id]) }}" method="POST">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-outline-dark btn-sm me-2 btn-delete">
                                                    <i class="bi-trash"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @endsection

    @push('scripts')
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.3.2/js/dataTables.fixedHeader.min.js"></script>
        <script type="module">
            $(document).ready(function() {
                $("#taskTable").DataTable({
                    responsive: true,
                    searching: false,
                    paging: false,
                    info: false
                });

                $(".tasktable").on("click", ".btn-delete", function (e) {
                    e.preventDefault();

                    var form = $(this).closest("form");

                    Swal.fire({
                        title: "Are you sure want to delete ?",
                        text: "You won't be able to revert this!",
                        icon: "warning",
                        showCancelButton: true,
                        confirmButtonClass: "bg-primary",
                        confirmButtonText: "Yes, delete it!",
                    }).then((result) => {
                        if (result.isConfirmed) {
                            form.submit();
                        }
                    });
                });

            });
        </script>
    @endpush

resources/views/workspaces/edit.blade.php
    @extends('layouts.sidebar')
    @section('content')
    <div class="container-sm">
        <h3 class="mt-3">Edit Workspace</h3>

        <div class="mb-3">
            <label class="form-label">Member Lists</label>
            <div style="height: 100px" class="card-footer overflow-y-scroll" id="scroll">
                <table class="table table-striped table-hover membertable">
                    {{-- {{ $workspace->id }} --}}
                    @foreach ( $usersName as $name )
                    <tr>
                        <td>{{ $name->name }}</td>
                        <td>{{ $name->email }}</td>
                        @if ($name->member->where('workspace_id','=',$workspace->id)->pluck('level')->first() == '1')
                        <td>Owner</td>
                        @else
                        <td>
                            <div>
                                <form action="{{ route('deleteUser') }}" method="POST">
                                    @csrf
                                    <input type="text" name="nameId" value="{{ $name->id }}" hidden>
                                    <input type="text" name="workspaceId" value="{{ $workspace->id }}" hidden>
                                    <button type="submit" class="btn btn-outline-dark btn-sm me-2 btn-delete">
                                        <i class="bi-trash"></i>
                                    </button>
                                </form>
                            </div>
                        </td>
                        @endif
                    </tr>
                    @endforeach
                </table>
            </div>
        </div>

        <form action="{{ route('workspaces.update',[$workspace->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input type="" class="form-control" id="user_id" name="user_id" value="{{ $sessionId }}" hidden>
            <div class="mb-3">
              <label for="workspaceName" class="form-label">Workspace's Name</label>
              <input type="text" class="form-control @error('workspaceName') is-invalid @enderror" id="workspaceName" name="workspaceName" value="{{ $workspace->namaWorkspace }}" >
              @error ('workspaceName') <div class="fs-3 text-danger">{{ $message }}</div> @enderror
            </div>

            <div class="mb-3">
              <label for="newName" class="form-label">Add member</label>
              <select class="form-control" id="newName" name="newName">
                <option value="" selected></option>
                @foreach ($user as $users )
                    <option value="{{ $users->id }}">{{ $users->email }}</option>
                @endforeach
              </select>
              <a href="javascript:void(0)" class="btn btn-secondary fs-3 mt-2" id="clearButton">Clear Selection</a>
            </div>

            <div class="mb-3">
              <label for="workspaceDesc" class="form-label">Description</label>
              <textarea class="form-control" placeholder="" id="workspaceDesc" style="height: 100px" name="workspaceDesc">{{ $workspace->deskWorkspace }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{{ route ('workspace') }}" type="button" id="submit" name="submit" class="btn btn-secondary">Cancel</a>
          </form>
    </div>
    @endsection

    @push('scripts')
    <script type="module">
        // For Select2 4.1

        $("#newName").select2({
            theme: "bootstrap-5",
            placeholder: "New Member",
            // minimumInputLength: 1,
            // ajax: {
            //     url: "",
            //     dataType: 'json',
            //     delay: 250,
            //     data: function (params) {
            //         return {
            //             q: params.term // Gunakan 'q' sebagai parameter untuk input pencarian
            //         };
            //     },
            //     processResults: function (data) {
            //         return {
            //             results: data
            //         };
            //     },
            //     cache: true
            // }
        });

        $('#clearButton').click(function () {
            $('#newName').val(null).trigger('change');
        });
    </script>
    @endpush

resources/views/workspaces/index.blade.php
    @extends('layouts.sidebar')

    @section('content')
    @vite('resources/js/datatable.js')
    <div class="container-sm">
        <div class="d-flex justify-content-between align-items-center">
            <h3 class="mt-3">List Workspace</h3>
            <div class="">
                <a href="{{ route ('workspaces.create') }}" class="btn btn-outline-primary px-5">Create</a>
            </div>
        </div>
        <div class="table-responsive border p-3 rounded-3 mb-3">
            {{-- {{ $available }} --}}
            @if (count($available) == 0)
                <a href="{{ route ('workspaces.create') }}" class="btn btn-outline-primary">Create new Workspace</a>
            @else
                <table class="table table-hover table-striped bg-white datatable" id="workspaceTable">
                    <thead>
                        <tr>
                            <th>Workspace</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            @endif
        </div>
    </div>
    @endsection
    @push('scripts')
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.3.2/js/dataTables.fixedHeader.min.js"></script>
        <script type="module">
            $(document).ready(function() {
                $("#workspaceTable").DataTable({
                    serverSide: true,
                    processing: true,
                    responsive: true,
                    ajax: "/getWorkspaces",
                    columns: [
                        { data: "namaWorkspace", name: "namaWorkspace" },
                        { data: "deskWorkspace", name: "deskWorkspace" },
                        { data: "actions", name: "actions", orderable: false, searchable: false }
                    ],
                    order: [[0, "desc"]],
                    lengthMenu: [
                        [10, 25, 50, 100, -1],
                        [10, 25, 50, 100, "All"],
                    ],
                });

                $(".datatable").on("click", ".btn-delete", function (e) {
                    e.preventDefault();

                    var form = $(this).closest("form");

                    Swal.fire({
                        title: "Are you sure want to delete ?",
                        text: "You won't be able to revert this!",
                        icon: "warning",
                        showCancelButton: true,
                        confirmButtonClass: "bg-primary",
                        confirmButtonText: "Yes, delete it!",
                    }).then((result) => {
                        if (result.isConfirmed) {
                            form.submit();
                        }
                    });
                });
            });

        </script>
    @endpush